import assert from 'node:assert/strict';
import {newGame,puzzleAction,puzzleOptions,placeTile,memoryAction,dotsAction,rpsAction,publicGame,boxEdges} from '../public/arcade.mjs';
for(const size of [3,4,6,8])for(const cut of ['squares','triangles']){let p=newGame('puzzle',{size,cut,rotate:true,peek:false});const count=size*size*(cut==='triangles'?2:1);assert.equal(p.board.length,count);assert.equal(new Set(p.tray).size,count);assert.equal(p.config.peek,false);p.rotations[0]=1;assert.equal(placeTile(p,0,0),null);for(let i=0;i<3;i++)p=puzzleAction(p,{action:'rotate',piece:0});assert.equal(p.rotations[0],0);p=placeTile(p,0,0);assert.equal(p.board[0],0);assert.equal(placeTile(p,0,0),null);for(let i=1;i<count;i++){p.rotations[i]=0;p=placeTile(p,i,i)}assert.equal(p.winner,'together')}
assert.deepEqual(puzzleOptions({size:500,cut:'bad',rotate:'yes'}),{size:4,cut:'squares',rotate:false,peek:true});
let s=newGame('memory');s.deck=['a','a','b','b','c','c','d','d','e','e','f','f','g','g','h','h'];assert.ok(publicGame(s,'rose').deck.every(v=>v===null));assert.equal(memoryAction(s,0,'cream'),null);s=memoryAction(s,0,'rose',1000);assert.equal(publicGame(s,'cream',1000).deck[0],'a');assert.equal(memoryAction(s,0,'rose',1000),null);s=memoryAction(s,2,'rose',1000);assert.equal(s.turn,'cream');assert.equal(memoryAction(s,1,'cream',1100),null);assert.equal(publicGame(s,'cream',1100).deck[2],'b');assert.ok(publicGame(s,'cream',2500).deck.every(v=>v===null));s=memoryAction(s,0,'cream',2500);s=memoryAction(s,1,'cream',2500);assert.equal(s.points.cream,1);assert.equal(s.turn,'cream');assert.equal(s.matched[0],'cream');for(let i=2;i<16;i+=2){s=memoryAction(s,i,'cream',3000);s=memoryAction(s,i+1,'cream',3000)}assert.equal(s.winner,'cream');
s=newGame('dots');for(const edge of [0,3,12])s=dotsAction(s,edge,s.turn);const side=s.turn;s=dotsAction(s,13,side);assert.equal(s.boxes[0],side);assert.equal(s.turn,side);assert.equal(s.points[side],1);assert.equal(dotsAction(s,13,side),null);for(let e=0;e<24;e++)if(!s.edges[e])s=dotsAction(s,e,s.turn);assert.ok(s.winner);assert.equal(s.points.rose+s.points.cream,9);
s=newGame('dots');const combined=new Set([...boxEdges(0),...boxEdges(1)]);combined.delete(13);for(const e of combined)s.edges[e]='cream';s=dotsAction(s,13,'rose');assert.equal(s.points.rose,2);assert.equal(s.turn,'rose');
s=newGame('rps');s=rpsAction(s,{choice:'rock'},'rose');assert.equal(publicGame(s,'cream').picks.rose,null);assert.equal(publicGame(s,'cream').opponentPicked,true);assert.equal(rpsAction(s,{choice:'paper'},'rose'),null);assert.equal(rpsAction(s,{action:'next'},'cream'),null);s=rpsAction(s,{choice:'scissors'},'cream');assert.equal(s.roundResult,'rose');assert.equal(publicGame(s,'cream').picks.rose,'rock');for(let i=0;i<2;i++){s=rpsAction(s,{action:'next'},'cream');s=rpsAction(s,{choice:'paper'},'cream');s=rpsAction(s,{choice:'scissors'},'rose')}assert.equal(s.winner,'rose');assert.equal(s.points.rose,3);assert.equal(rpsAction(s,{action:'next'},'rose'),null);
console.log('Expansion checks passed: puzzle cuts/rotation/completion, memory privacy/timing/scoring, double-box capture, secret throws and first-to-three wins.');
