import assert from 'node:assert/strict';
import {newGarden,growGarden,gardenAction,DAY,levelOf,quests,ITEMS} from '../public/garden-rules.mjs';
const t=1800000000000,actor={id:'dylan',name:'Dylan'},other={id:'audrey',name:'Audrey'};
let s=newGarden(t);
const act=(body,who=actor,now=t)=>{const request={...body,requestId:crypto.randomUUID()};s=gardenAction(s,request,who,now).state;return request;};
const planted=act({action:'plant',seed:'tulip',plot:0});
assert.equal(s.plots.filter(Boolean).length,1);
assert.deepEqual(gardenAction(s,planted,actor,t).state,s,'retry cannot duplicate rewards');
assert.throws(()=>act({action:'plant',seed:'moon',plot:1}),/unlocked/);
assert.throws(()=>act({action:'plant',seed:'rose',plot:-1}),/plot/);
assert.throws(()=>act({action:'harvest',plot:0}),/blooming/);
act({action:'pet'},other);assert.equal(s.bondDays,1);assert.equal(s.streak,1);
assert.equal(quests(s).find(q=>q.id==='pet').count,2);
act({action:'claim',quest:'pet'});const coins=s.coins;
assert.throws(()=>act({action:'claim',quest:'pet'}),/not ready/);assert.equal(s.coins,coins);
const fresh=growGarden(s,t+31*60000);assert.equal(fresh.plots[0].growth,100);
act({action:'harvest',plot:0},actor,t+31*60000);assert.equal(s.plots[0],null);assert.equal(s.food,6);
act({action:'plant',seed:'rose',plot:2},actor,t+32*60000);
assert.equal(growGarden(s,t+2*DAY).plots[2].withered,true);
act({action:'revive',plot:2},actor,t+2*DAY);assert.equal(s.plots[2].withered,false);
act({action:'pet'},other,t+2*DAY);assert.equal(s.streak,1,'missing a day resets only the streak');assert.equal(s.bondDays,2,'earned together days persist');
act({action:'sleep'},actor,t+2*DAY);const asleep=growGarden(s,t+2*DAY+3600000);assert.ok(asleep.energy>s.energy);assert.ok(asleep.hunger<=s.hunger);assert.ok(asleep.hunger>=0);
assert.throws(()=>act({action:'feed'},actor,t+2*DAY+3600000),/Wake/);
act({action:'wake'},actor,t+2*DAY+3600000);act({action:'feed',snack:'garden'},actor,t+2*DAY+3600000);assert.equal(s.food,5);
act({action:'outfit',item:'daisy'},actor,t+2*DAY+3600000);assert.equal(s.outfit.hat,'daisy');const after=s.coins;act({action:'outfit',item:'daisy'},actor,t+2*DAY+3600000);assert.equal(s.coins,after,'owned cosmetics are not charged twice');
assert.throws(()=>act({action:'outfit',item:'rainbow'}),/unlock/);
assert.throws(()=>act({action:'color',color:'url(evil)'}),/color/);
assert.ok(ITEMS.length>=20);assert.ok(levelOf(s)>=1);assert.ok(s.log.length<=40);
console.log('Shared garden: offline growth, revival, harvests, food, sleep, shared streaks, quests, locked cosmetics and idempotent rewards passed.');
