import assert from 'node:assert/strict';
import {RacePrediction} from '../public/grand-prix-client.mjs';
import {gpNew,gpAction,gpAdvance} from '../public/grand-prix.mjs';
let server=gpAction(gpNew({config:{bots:0}}),{action:'ready'},'rose',10000,{solo:true,host:true});
server=gpAdvance(server,server.startAt+10);
server.cars[0].speed=15;
const client=new RacePrediction(),base=server.lastAt;
client.accept(server,base,'rose',{throttle:true});
const original=structuredClone(server);
for(let i=1;i<=35;i++)client.advance(base+i*16,'rose',{throttle:true,right:true});
assert.ok(client.state.cars[0].distance>original.cars[0].distance+5,'movement continues beyond old 250ms cutoff');
const steer=client.state.cars[0].steer;
client.advance(base+576,'rose',{throttle:true,left:true});
assert.ok(client.state.cars[0].steer<steer,'opposite steering responds on next frame without server reply');
assert.deepEqual(server,original,'prediction does not mutate authoritative state');
assert.equal(client.accept(server,base+600,'rose',{}),false,'duplicate replies do not rewind simulation');
const paused=structuredClone(server);paused.lastAt+=600;paused.pausedBy='rose';
assert.equal(client.accept(paused,base+600,'rose',{}),true);
const d=client.state.cars[0].distance;client.advance(base+616,'rose',{throttle:true});
assert.equal(client.state.cars[0].distance,d,'server pause remains authoritative');
assert.equal(client.accept(server,base+650,'rose',{}),false,'out of order replies ignored');
console.log('Prediction: immediate steering, 560ms delayed transport, duplicate/stale replies, pause, immutable server snapshots passed.');
