import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Heart,Flower2,Sprout,Droplets,Sun,Moon,Leaf,Shirt,Sparkles,Lock,Check,ArrowLeft,RefreshCw,Flame,Utensils,CloudSun,Gift,Plus,PenLine,Link,ChevronRight,X} from 'lucide-react';
import {Ladybug,Plant,Flower} from './garden-art.jsx';
import {PLANTS,ITEMS,levelOf,stageOf,quests,newGarden,growGarden,gardenAction} from '../public/garden-rules.mjs';

const demo=new URLSearchParams(location.search).has('preview');
const ago=t=>{const minutes=Math.max(0,Math.floor((Date.now()-t)/60000));return minutes<1?'just now':minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`;};
function App(){
 const [data,setData]=useState(null),[tab,setTab]=useState('garden'),[section,setSection]=useState('care'),[error,setError]=useState(''),[gate,setGate]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(true),[feedback,setFeedback]=useState(''),[emotion,setEmotion]=useState(''),[seedPlot,setSeedPlot]=useState(null),[slot,setSlot]=useState('hat'),[name,setName]=useState(''),[renaming,setRenaming]=useState(false),[retry,setRetry]=useState(null),[demoPartner,setDemoPartner]=useState(false);
 const current=useRef(null),locked=useRef(false),demoState=useRef(newGarden(Date.now())),feedbackTimer=useRef(null);
 const accept=incoming=>{const old=current.current;if(old&&(incoming.revision<old.revision||(incoming.revision===old.revision&&incoming.now<old.now)))return;current.current=incoming;setData(incoming);setOnline(true);setGate('');};
 async function load(){if(locked.current||document.hidden)return;try{if(demo){accept({state:growGarden(demoState.current,Date.now()),revision:current.current?.revision||0,now:Date.now(),user:{id:'you',name:'You'},partner:'Your person'});return;}const r=await fetch('/api/notes/garden',{cache:'no-store',signal:AbortSignal.timeout(12000)}),d=await r.json();if(!r.ok){if(r.status===401||r.status===403){setGate(d.error);setData(null);current.current=null;}else throw Error(d.error);return;}accept(d);}catch(e){setOnline(false);if(!current.current)setError(e.message||'Could not reach your garden.');}}
 useEffect(()=>{load();const timer=setInterval(load,5000);const wake=()=>{if(!document.hidden)load();};document.addEventListener('visibilitychange',wake);window.addEventListener('online',wake);return()=>{clearInterval(timer);clearTimeout(feedbackTimer.current);document.removeEventListener('visibilitychange',wake);window.removeEventListener('online',wake);};},[]);
 useEffect(()=>{if(seedPlot===null)return;const previous=document.activeElement;const handler=e=>{if(e.key==='Escape')setSeedPlot(null);if(e.key==='Tab'){const buttons=[...document.querySelectorAll('.seed-modal button:not(:disabled)')];const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus();};},[seedPlot]);
 async function act(body){if(locked.current)return;locked.current=true;setBusy(true);setError('');const request={...body,requestId:body.requestId||crypto.randomUUID()};try{let d;if(demo){const result=gardenAction(demoState.current,request,{id:demoPartner?'partner':'you',name:demoPartner?'Your person':'You'},Date.now());demoState.current=result.state;d={...current.current,state:result.state,message:result.message,revision:(current.current?.revision||0)+1,now:Date.now()};}else{let response;for(let i=0;i<2;i++){response=await fetch('/api/notes/garden',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request),signal:AbortSignal.timeout(12000)});d=await response.json();if(response.status!==409)break;}if(!response.ok)throw Error(d.error||'That action could not be saved.');}accept(d);setRetry(null);setSeedPlot(null);setRenaming(false);setFeedback(d.message);setEmotion(body.action);clearTimeout(feedbackTimer.current);feedbackTimer.current=setTimeout(()=>{setEmotion('');setFeedback('');},4200);}catch(e){setError(e.message||'Could not save. Your garden is safe—try again.');setRetry(request);}finally{locked.current=false;setBusy(false);}}
 const s=data?.state,level=s?levelOf(s):1;
 const careReady=key=>!busy&&(!s.cooldowns[key]||Date.now()-s.cooldowns[key]>=30000);
 function demoGrow(){demoState.current=growGarden(demoState.current,Date.now()+3600000);demoState.current.updatedAt=Date.now();accept({...current.current,state:demoState.current,revision:(current.current?.revision||0)+1,now:Date.now()});}
 return <div className="garden-app min-h-screen">
 <header className="garden-header"><a href="/" className="brand"><Heart size={21} fill="currentColor"/>Two Lovebugs</a><nav aria-label="Main"><a href="/">Arcade</a><a href="/notes">Love Notes</a><a href="/garden" aria-current="page">Our world <Leaf size={15}/></a></nav></header>
 <main className="garden-main mx-auto max-w-6xl px-4 md:px-8">
 {demo&&<div className="demo-banner"><span>Preview garden · changes stay in this tab</span><button onClick={()=>setDemoPartner(!demoPartner)}>Playing as {demoPartner?'your person':'you'}</button><button onClick={demoGrow}>Preview 1 hour of growth</button><a href="/garden">Open our real garden →</a></div>}
 <div className="page-heading"><div><p className="eyebrow"><Sprout size={15}/> SOMETHING WE GROW TOGETHER</p><h1>Our corner of the <em>world.</em></h1><p className="intro">A garden to tend. A lovebug to spoil. Always ours.</p></div><div className="pair-chip"><span className="pair-hearts"><Heart size={18}/><Heart size={18}/></span>{data?<span>{data.user.name} & {data.partner}<small><i className={online?'connected':'offline'}/>{demo?'Preview garden':online?'Shared garden · saved':'Reconnecting…'}</small></span>:<span>Made for two<small>Connected through Love Notes</small></span>}</div></div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>retry?act(retry):(setError(''),load())}><RefreshCw size={15}/>Try again</button></div>}
 {!s?<section className="welcome card"><div className="welcome-art"><Ladybug outfit={{hat:'bow',color:'#df8da8'}}/></div><p className="eyebrow">YOUR NEXT CHAPTER</p><h2>{gate?'A world for the two of you.':error?'Your garden is taking a moment.':'Opening your garden…'}</h2><p>{gate||'Finding your shared ladybug and plants.'}</p>{gate&&<><a className="primary" href="/notes"><Link size={17}/>Sign in or connect in Love Notes</a><p className="fine">Already connected? Use the same account, then open “Our Garden” from Love Notes.</p></>}<a className="text-link" href="/garden?preview=1">Take a peek at a preview garden <ChevronRight size={15}/></a></section>:<>
 <div className="garden-toolbar"><div role="tablist" aria-label="Your shared world" className="main-tabs">{[['garden','Our Garden',Flower2],['pet','Our Ladybug',Heart]].map(([id,label,Icon])=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon size={19}/>{label}</button>)}</div><div className="wallet"><span title="Earn dewdrops from quests and harvests"><Droplets size={18}/>{s.coins}<small>dewdrops</small></span><span title="Harvest plants to earn garden treats"><Leaf size={18}/>{s.food}<small>treats</small></span></div></div>
 <div className="world-layout grid gap-5 lg:grid-cols-[minmax(0,1fr)_310px]">
 <section className="world-left min-w-0" aria-label={tab==='garden'?'Our Garden':'Our Ladybug'}>
 {tab==='garden'?<><div className="garden-scene card"><div className="scene-heading"><div><p className="eyebrow">THE GARDEN PATCH</p><h2>A little care, a lot of bloom.</h2></div><span className="weather"><CloudSun size={25}/><small>Soft skies</small></span></div><div className="garden-field"><div className="garden-fence"/><div className="plot-grid grid grid-cols-2 sm:grid-cols-3 gap-3">{s.plots.map((p,i)=>{const seed=p&&PLANTS[p.type],ready=p&&p.growth>=100&&!p.withered,cooled=s.cooldowns['plot:'+i]&&Date.now()-s.cooldowns['plot:'+i]<60000;return <article className={`soil-plot ${p?'planted':''}`} key={i}><div className="plot-art">{p?<Plant type={p.type} growth={p.growth} withered={p.withered}/>:<div className="empty-seed"><Sprout size={29}/><span>A place to grow</span></div>}</div><div className="plot-info"><strong>{seed?.name||`Plot ${i+1}`}</strong>{p?<><span>{p.withered?'A little thirsty':ready?'Ready to harvest':p.growth<35?'Seedling':p.growth<80?'Sprout':'Nearly blooming'}</span><div className="growth-track" role="progressbar" aria-label={`${seed.name} growth`} aria-valuenow={Math.round(p.growth)} aria-valuemin={0} aria-valuemax={100}><i style={{width:p.growth+'%'}}/></div><button disabled={busy||(!ready&&cooled)} onClick={()=>act({action:p.withered?'revive':ready?'harvest':'water',plot:i})}>{p.withered?<><Heart size={14}/>Revive</>:ready?<><Leaf size={14}/>Harvest</>:<><Droplets size={14}/>{cooled?'Freshly watered':'Water'}</>}</button></>:<button disabled={busy} onClick={()=>setSeedPlot(i)}><Plus size={15}/>Plant a seed</button>}</div></article>})}</div><div className="field-bottom"><span>✿</span><p>Every bloom is a treat for {s.name}.</p><span>✿</span></div></div></div><div className="garden-tip"><Sun size={20}/><p>Plants grow while you’re away. Water once a day to keep them happy. Revive any dry plant—nothing is lost.</p></div></>:<div className="pet-card card"><div className="scene-heading"><div><p className="eyebrow">OUR VERY OWN LOVEBUG</p><h2>{s.name}<button className="edit-name" onClick={()=>{setRenaming(!renaming);setName(s.name)}} aria-label="Rename ladybug"><PenLine size={17}/></button></h2></div><span className="stage-pill">{stageOf(s)}</span></div>{renaming&&<form className="rename-form" onSubmit={e=>{e.preventDefault();act({action:'rename',name})}}><input aria-label="Ladybug name" value={name} maxLength={24} onChange={e=>setName(e.target.value)}/><button disabled={busy}>Save name</button><button type="button" onClick={()=>setRenaming(false)}>Cancel</button></form>}
 <div className={`pet-meadow ${s.sleeping?'night':''}`}><div className="meadow-cloud cloud-one"/><div className="meadow-cloud cloud-two"/><span className="meadow-sun">{s.sleeping?<Moon size={30}/>:<Sun size={30}/>}</span><div className="mood-bubble">{s.sleeping?'Snoring under my leaf cozy…':emotion?'You make my antennae wiggle!':s.hunger<30?'A snack and a cuddle, please?':s.affection<30?'I saved you a spot beside me.':s.energy<25?'Big yawn. Leaf bed soon?':'Oh! My favorite humans.'}</div><button className="pet-touch" aria-label={`Gently pet ${s.name}`} disabled={!careReady('pet')||s.sleeping} onClick={()=>act({action:'pet'})}><Ladybug outfit={s.outfit} sleeping={s.sleeping} level={level} mood={s.hunger<30?'hungry':'happy'} emotion={emotion}/></button><svg className="meadow-flowers" viewBox="0 0 600 90" aria-hidden="true">{[30,62,110,460,510,560].map((x,i)=><g key={x}><path d={`M${x} 90v-${25+i%3*15}`} stroke="#85a781" strokeWidth="3"/><Flower x={x} y={65-i%3*15} color={i%2?'#eed48d':'#e9adc2'} size={.7}/></g>)}</svg></div>
 <div className="vitals grid grid-cols-3 gap-4">{[['hunger','Full tummy',Utensils],['affection','Affection',Heart],['energy','Energy',Moon]].map(([key,label,Icon])=><div key={key}><div><Icon size={15}/><span>{label}</span><strong>{Math.round(s[key])}%</strong></div><div className={'vital-track '+key}><i style={{width:s[key]+'%'}}/></div></div>)}</div>
 <div className="pet-tabs"><button className={section==='care'?'selected':''} onClick={()=>setSection('care')}><Heart size={17}/>Care & cuddles</button><button className={section==='closet'?'selected':''} onClick={()=>setSection('closet')}><Shirt size={17}/>Dress up <span>{s.owned.length-3}</span></button></div>
 {section==='care'?<div className="care-actions grid grid-cols-2 gap-3"><button disabled={!careReady('feed')||s.sleeping||s.hunger>95} onClick={()=>act({action:'feed',snack:'aphid'})}><Utensils/><strong>Aphid snack</strong><small>Always free · +15 tummy</small></button><button disabled={!careReady('feed')||!s.food||s.sleeping||s.hunger>95} onClick={()=>act({action:'feed',snack:'garden'})}><Leaf/><strong>Garden treat</strong><small>Use 1 treat · +30 tummy</small></button><button disabled={!careReady('pet')||s.sleeping} onClick={()=>act({action:'pet'})}><Heart/><strong>Gently pet</strong><small>Antennae wiggles included</small></button><button disabled={busy} onClick={()=>act({action:s.sleeping?'wake':'sleep'})}>{s.sleeping?<Sun/>:<Moon/>}<strong>{s.sleeping?'Good morning':'Leaf bedtime'}</strong><small>{s.sleeping?'Wake our sleepy lovebug':'Restores 22 energy / hour'}</small></button></div>:<div className="closet"><div className="closet-heading"><div className="slot-tabs">{['hat','glasses','aura'].map(t=><button key={t} className={slot===t?'selected':''} onClick={()=>setSlot(t)}>{t==='hat'?'Hats':t==='glasses'?'Glasses':'Auras'}</button>)}</div><label className="shell-picker">Shell<input type="color" aria-label="Shell color" value={s.outfit.color} disabled={busy} onChange={e=>act({action:'color',color:e.target.value})}/></label></div><div className="outfit-grid grid grid-cols-3 sm:grid-cols-4 gap-2">{ITEMS.filter(i=>i.slot===slot).map(item=>{const locked=item.level>level||(item.days||0)>s.bondDays,owned=s.owned.includes(item.id),equipped=s.outfit[item.slot]===item.id;return <button className={`outfit ${equipped?'equipped':''}`} key={item.id} disabled={busy||locked||(!owned&&s.coins<item.cost)||equipped} onClick={()=>act({action:'outfit',item:item.id})} aria-label={`${item.name}, ${locked?'locked':owned?'equip':item.cost+' dewdrops'}`}><div className="outfit-art"><Ladybug mini outfit={{...s.outfit,[item.slot]:item.id}}/>{locked&&<span className="lock-badge"><Lock size={14}/></span>}</div><strong>{item.name}</strong><small>{equipped?'Wearing it ♡':locked?`Level ${item.level}${item.days?` · ${item.days} together days`:''}`:owned?'Owned':`${item.cost} dewdrops`}</small></button>})}</div></div>}
 </div>}
 </section>
 <aside className="space-y-5"><section className="companion-card card"><div className="companion-heading"><p className="eyebrow">GROWING UP TOGETHER</p><span>LV. {level}</span></div><button className="companion-link" onClick={()=>setTab('pet')}><div className="companion-avatar"><Ladybug mini outfit={s.outfit} sleeping={s.sleeping}/></div><div><h3>{s.name}</h3><p>{stageOf(s)}</p></div><ChevronRight size={18}/></button><div className="level-track"><i style={{width:(level===10?100:s.xp%80/80*100)+'%'}}/></div><p className="level-caption">{level===10?'Fully bloomed. Still growing memories.':`${80-s.xp%80} care points to level ${level+1}`}</p><div className="bond-row"><Flame size={19}/><div><strong>{s.lastBondDay<Math.floor(Date.now()/86400000)-1?0:s.streak} day together streak</strong><span>{s.bondDays} days cared for by both of you</span></div></div><p className="fine">Both of you care each day to keep the streak. Earned days and outfits stay forever.</p></section>
 <section className="quests card"><div className="section-title"><h3>Today’s small joys</h3><Sparkles size={19}/></div><p className="fine">A few things to do, together.</p>{quests(s).map(q=>{const done=s.daily.claimed.includes(q.id),ready=q.count>=q.target;return <div className="quest" key={q.id}><span className={`quest-icon ${ready?'ready':''}`}>{done?<Check size={16}/>:q.id==='water'?<Droplets size={17}/>:q.id==='feed'?<Utensils size={17}/>:q.id==='pet'?<Heart size={17}/>:<Sprout size={17}/>}</span><div><strong>{q.name}</strong><p>{q.detail}</p><small>{Math.min(q.target,q.count)}/{q.target} · {q.coins} dewdrops</small></div><button aria-label={`Collect ${q.name} reward`} disabled={busy||!ready||done} onClick={()=>act({action:'claim',quest:q.id})}>{done?<Check size={15}/>:ready?<Gift size={18}/>:<span>{Math.min(q.count,q.target)}/{q.target}</span>}</button></div>})}<p className="reset-note">New quests at midnight UTC · care at your own pace.</p></section>
 <section className="next-unlock card"><Sparkles size={22}/><div><h3>Something to look forward to</h3><p>{level<2?'Level 2 brings a sunhat, heart glasses, and tiny cacti.':level<4?'Keep tending: a mushroom cap, star flowers, and petal breezes await.':level<7?'Shared care days unlock a flower crown, fireflies, and a rainbow aura.':'You’ve grown a garden guardian. There are still outfits to collect.'}</p></div></section></aside>
 </div>
 <section className="activity card"><div className="section-title"><div><p className="eyebrow">TRACES OF US</p><h2>While you were here.</h2></div><Heart size={21}/></div>{s.log.length?<ol>{s.log.slice(0,8).map(entry=><li key={entry.id}><span className="activity-dot"><Leaf size={15}/></span><p><strong>{entry.name}</strong> {entry.text}</p><time dateTime={new Date(entry.at).toISOString()}>{ago(entry.at)}</time></li>)}</ol>:<p className="empty-log">Your story starts with a seed. Plant something and leave your first trace.</p>}</section>
 </>}
 <footer className="garden-footer"><Flower2 size={17}/>Different places. The same patch of sunshine.<Heart size={14}/></footer>
 </main>
 {feedback&&<div className="garden-toast" role="status"><Heart size={18}/>{feedback}</div>}
 {seedPlot!==null&&s&&<div className="modal-backdrop" onClick={()=>setSeedPlot(null)}><section className="seed-modal card" role="dialog" aria-modal="true" aria-labelledby="seed-title" onClick={e=>e.stopPropagation()}><div className="section-title"><div><p className="eyebrow">A NEW BEGINNING</p><h2 id="seed-title">What shall we grow?</h2></div><button autoFocus aria-label="Close seed picker" onClick={()=>setSeedPlot(null)}><X/></button></div><p>Seeds are free. Blooms become treats, dewdrops, and a reason to visit.</p><div className="seed-grid grid grid-cols-2 sm:grid-cols-3 gap-3">{Object.entries(PLANTS).map(([id,p])=><button disabled={busy||p.level>level} key={id} onClick={()=>act({action:'plant',plot:seedPlot,seed:id})}><Plant type={id}/><strong>{p.name}</strong><small>{p.level>level?`Unlocks at level ${p.level}`:`${p.minutes} min · ${p.food} treats`}</small>{p.level>level?<Lock size={15}/>:<span>Plant <Plus size={13}/></span>}</button>)}</div></section></div>}
 </div>;
}
createRoot(document.getElementById('garden-root')).render(<App/>);
